print("Scripting System Starting Up!!!")
print("-- version:", game.versionNumber())
print("-- device type:", game.getDeviceType())
print("-- device OS:", game.getDeviceOs())
print("-- screen width:", lua_sys.screenWidth())
print("-- screen height:", lua_sys.screenHeight())
print("-- HUD scale:", game.hudScale())
print("-- MenuScaleX:", game.menuScaleX())
print("-- MenuScaleY:", game.menuScaleY())
print("====== GL INFO =====")
print("GL Version: ", game.glVersion())
print("GL Vendor: ", game.glVendor())
print("GL Renderer: ", game.glRenderer())
print("GL Shading Language: ", game.glShadingLanguage())
print("GL Extensions: ", game.glExtensions())
